### ISSUE TITLE
Getting message: "environments" is not supported by Apple Pay

### ISSUE THREAD

**Issue by andreycast** [MadBrains/Mad-Pay-Flutter#19]
I'm getting an error when doing a preflight check:
  

```
 final bool req =  await pay.checkPayments();
      final bool req1 = await pay.checkActiveCard(
        paymentNetworks: <PaymentNetwork>[
          PaymentNetwork.visa,
          PaymentNetwork.mastercard,
        ],
      );
```

`[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Response(success: true, errorCode: notImplemented, message: "environments" is not supported by Apple Pay, data: null)`

Any ideas why this could be happening?

**Comment by mit-73** [comment]
Hi @andreycast, no need to worry. It's not an error, it's an informational message.

In a [future update](https://pub.dev/packages/mad_pay/versions/2.2.0-beta.6), we have removed it so that such cases don't happen.
