### ISSUE TITLE
Suggestion: allow to only supply single Platform (AppleParameters or GoogleParameters) 

### ISSUE THREAD

**Issue by abdulaziz-mohammed** [MadBrains/Mad-Pay-Flutter#21]
or define a 'none' constructor e.g.
`google: GoogleParameters.none`

**Comment by mit-73** [comment]
It will appear in the future: https://github.com/MadBrains/Mad-Pay-Flutter/blob/main/packages/mad_pay_platform_interface/lib/src/models/processing_payment.dart#L23-L46

You can now try it in the [beta](https://pub.dev/packages/mad_pay/versions/2.2.0-beta.7)

**Comment by mit-73** [comment]
A library update has been released that adds this capability. I close this issue.
