### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vanomak** [MadBrains/Mad-Pay-Flutter#23]
mad_pay: 2.2.0

Can't compile it. Cleaning did not help 8(

Running Gradle task 'assembleDebug'...
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (53, 19): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (58, 19): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (66, 19): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (76, 19): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (98, 50): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (100, 50): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (101, 32): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (106, 52): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (108, 13): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (136, 53): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (140, 45): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (141, 41): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (157, 37): Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\MadPayAndroidPlugin.kt: (158, 25): Unresolved reference: it
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (3, 37): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (4, 37): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (14, 58): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (16, 17): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (17, 17): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (18, 17): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (19, 17): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (20, 17): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (25, 56): Unresolved reference: CardAuthMethods
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (27, 17): Unresolved reference: CardAuthMethods
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (28, 17): Unresolved reference: CardAuthMethods
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (33, 55): Unresolved reference: TotalPriceStatus
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (35, 17): Unresolved reference: TotalPriceStatus
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (36, 17): Unresolved reference: TotalPriceStatus
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (37, 17): Unresolved reference: TotalPriceStatus
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (42, 50): Unresolved reference: CheckoutOption
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (44, 17): Unresolved reference: CheckoutOption
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (45, 17): Unresolved reference: CheckoutOption
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (50, 53): Unresolved reference: PaymentNetwork
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\PaymentHelpers.kt: (58, 46): Unresolved reference: CardAuthMethods
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (16, 54): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (16, 108): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (24, 50): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (24, 104): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (53, 58): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (63, 48): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (77, 77): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (111, 67): Unresolved reference: MadPay
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (120, 38): Unresolved reference: Google
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\mad_pay_android-2.2.0\android\src\main\kotlin\ru\madbrains\mad_pay_android\RawMethods.kt: (120, 92): Unresolved reference: MadPay

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mad_pay_android:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by taxodima** [comment]
Same problem...

**Comment by takumade** [comment]
update your kotlin version in android `build.gradle` to:
`
ext.kotlin_version = '1.4.32'`

**Comment by mrchuis** [comment]
> update your kotlin version in android `build.gradle` to:
> ` ext.kotlin_version = '1.4.32'`

Your solution doesn't help :(

**Comment by Antol** [comment]
Can you provide more information about the environment? 
- Flutter version
- Dart version
- Kotlin version
- Gradle version
- pubspec.yaml, pubspec.lock files
- build.gradle app/build.gradle files

Does the example project in that lib gives you the error?

**Comment by mit-73** [comment]
Corrected in version [2.2.1](https://pub.dev/packages/mad_pay/versions/2.2.1), should now build a release build. If you still have a problem, describe it in more detail and provide more information about the environment.

**Comment by mit-73** [comment]
Fixed it in version [2.2.2](https://pub.dev/packages/mad_pay/versions/2.2.2), should now build a release build. If you still have a problem, describe it in more detail and provide more information about the environment!

**Comment by mrchuis** [comment]
> Fixed it in version [2.2.2](https://pub.dev/packages/mad_pay/versions/2.2.2), should now build a release build. If you still have a problem, describe it in more detail and provide more information about the environment!

The new version solved this problem! Thanks!
