### ISSUE TITLE
Typo for contact email address property

### ISSUE THREAD

**Issue by ZiyadF296** [MadBrains/Mad-Pay-Flutter#29]
Hello,

I think that I found a major typo in this plugin. The typo is in the contact class. The email address property is called `emailAddres` with one `s`. It should be `emailAddress` with 2 `s`. Other than that, the plugin is great!

Thank you and hopefully, the fix is updated soon since typos is kind of a freak out for me 😅

**Comment by mit-73** [comment]
Thank you @ZiyadF296 for finding the typo, even though it was not serious I could not go by and not fix it. Fixes are available in version [2.2.5](https://pub.dev/packages/mad_pay/versions/2.2.5)
