### ISSUE TITLE
An unexpected error has occured. Please try again later. [OR-BIBED_01]

### ISSUE THREAD

**Issue by michaelgobbers** [MadBrains/Mad-Pay-Flutter#46]
I'm currently trying out the google pay integration (Gateway setup) and I'm getting the error in this issue title when targetting the pay test environment? I was wondering if you encountered this before?

**Comment by mit-73** [comment]
It is difficult to say what is the reason, you need to look logcat key wallet or pay.

**Comment by michaelgobbers** [comment]
I've been going through logcat but nothing is in there. Have you been able to use this library for google pay in your apps (using a processor gateway)?

**Comment by mit-73** [comment]
Yes, of course we use mad_pay to pay in our apps. But your error seems to be either with a business account (which needs to be done) or with an error on the device. Either way there must be something in the logcat, take a closer look.

**Comment by michaelgobbers** [comment]
only thing I seem to find is the following (Which I think is more debug info)
`02-07 17:23:01.063  2167  8254 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.067  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.067  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.067  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.068  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.068  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.091  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.092  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.092  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.092  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.092  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.102  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.102  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.102  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.102  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.102  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.113  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.113  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.113  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.114  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.114  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.128  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.129  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.129  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.130  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.130  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.136  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.136  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.137  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.137  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.137  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.142  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.142  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.142  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.142  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.143  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.146  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.146  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.147  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.147  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.147  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.155  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.155  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.155  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.155  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.155  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]
02-07 17:23:01.160  2167 31422 W TapAndPay: platformSupportsGooglePay: true [CONTEXT service_id=79 ]
02-07 17:23:01.160  2167 31422 W TapAndPay: hasManagedProfile: false [CONTEXT service_id=79 ]
02-07 17:23:01.161  2167 31422 W TapAndPay: isChromeOsDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.161  2167 31422 W TapAndPay: isUncertifiedDevice: false [CONTEXT service_id=79 ]
02-07 17:23:01.161  2167 31422 W TapAndPay: deviceSupportsTokenization: true [CONTEXT service_id=79 ]`

**Comment by michaelgobbers** [comment]
So. I've been able to identify that it's related with passing in the paymentNetworks. If I pass in a null value there, all seems to be working. I'll see if I can get some more info on why this is...

**Comment by michaelgobbers** [comment]
I narrowed it down to the payment network `interac` this is defined in the platform interface as `interact` this is wrong and a bug. I'll create a PR for this bugfix.

**Comment by michaelgobbers** [comment]
#48 https://github.com/MadBrains/Mad-Pay-Flutter/pull/48

**Comment by michaelgobbers** [comment]
Opened a MR, @mit-73 let me know if theres anything I can do to get it merged.

**Comment by mit-73** [comment]
Thanks @michaelgobbers, wrote what needs to be done!

**Comment by mit-73** [comment]
Closing this issue, the PR has been merged.
