### ISSUE TITLE
MIR support for iOS

### ISSUE THREAD

**Issue by alex-dorokhov** [MadBrains/Mad-Pay-Flutter#47]
MIR is technically available on iOS (https://mironline.ru/press-center/press-releases/20-07-2021-apple-pay-stanovitsya-dostupen-derzhatelyam-kart-platezhnoy-sistemy-m/)
Many acquirers have also added a support to it in combination with ApplePay (e.g. Tinkoff). They have updated their native library to support that.
Could you please add a support for MIR to MadPay?
Thank you.

**Comment by mit-73** [comment]
Added support in version [2.2.12](https://pub.dev/packages/mad_pay/versions/2.2.12)
