### ISSUE TITLE
billingContact and shippingContact for Apple Pay

### ISSUE THREAD

**Issue by urusai88** [MadBrains/Mad-Pay-Flutter#5]
What about it?
https://developer.apple.com/documentation/passkit/pkpaymentrequest

**Comment by mit-73** [comment]
Hi, @urusai88 I'm already working on this

**Comment by urusai88** [comment]
> Hi, @urusai88 I'm already working on this

Oh, me started to work on this too

**Comment by mit-73** [comment]
@urusai88, Added options for Apple Pay #6 (also updated 2.0.2 on pub). I will close the issue.
