### ISSUE TITLE
Method get token of PaymentResponce class throws exception even if token does exist.

### ISSUE THREAD

**Issue by Aleblood** [MadBrains/Mad-Pay-Flutter#57]
Здравствуйте!

It seems to happen because deepSearch method that is used by PaymentResponse.token looks only in first branches of "map tree".

This is the way I fixed it:

```
extension _MapX<K, V> on Map<K, V> {
  dynamic deepSearch(K key) {
    if (this[key] != null) return this[key];
    
    for (final dynamic value in values) {
      if (value is Map) {
        final token = value.deepSearch(key);
        if (token != null) return token;
      }
    }
  }
}
```

**Comment by mit-73** [comment]
Hi @Aleblood, thanks for your issue, it was indeed a serious bug. We have fixed it in [version 2.2.14](https://pub.dev/packages/mad_pay).
