### ISSUE TITLE
Type CardAuthMethods not properly exported

### ISSUE THREAD

**Issue by TomKrauss** [MadBrains/Mad-Pay-Flutter#7]
One cannot define the list of allowed card authentication methods (Parameter to class `GoogleParameters`), as the required enum type `CardAuthMethods` is not properly exported by the mad pay library. As a work around one can import the type from the implementation file directly, but it should ideally be exported (exported and shown) from library mad_pay

**Comment by mit-73** [comment]
@TomKrauss, sorry initially misunderstood you. Added export #8, and updated the version on pub to 2.0.3.
I close this issue.

**Comment by TomKrauss** [comment]
Thank you very much mit-73 - that was fast :-)
